import {isListingImageUrl} from './image-url';
import {z} from "zod";
export const dongs=["공덕동","아현동","도화동","용강동","대흥동","염리동","신수동","서교동","합정동","망원동","연남동","성산동","상암동","상수동","하중동","당인동","노고산동","신정동","구수동","현석동","토정동","마포동","동교동","중동"];
const optionSchema=z.object({price:z.number().finite().min(0).max(10000000),rent:z.number().finite().min(0).max(100000)});
export const listingSchema=z.object({id:z.string().trim().min(1).max(100),district:z.literal("마포구"),dong:z.string().refine(v=>v==="동 정보 없음"||dongs.includes(v),"마포구 법정동 또는 동 정보 없음을 입력하세요"),name:z.string().trim().min(1).max(150),type:z.enum(["원룸","오피스텔"]),deal:z.enum(["전세","월세"]),price:z.number().finite().min(0).max(10000000),rent:z.number().finite().min(0).max(100000).default(0),area:z.number().finite().positive().max(10000),floor:z.string().max(30).default("층 정보 없음"),trackable:z.boolean().default(true),priceOptions:z.array(optionSchema).min(1).max(2).optional(),priceText:z.string().max(200).optional(),sourcePriceText:z.string().max(250).optional(),sourceRow:z.number().int().positive().optional(),sourceFile:z.string().max(150).optional(),sourceSheet:z.string().max(30).optional(),sourceCollectedAt:z.string().max(40).optional(),sourceDate:z.string().max(10).optional(),imageUrl:z.string().max(2000).refine(isListingImageUrl,"네이버 이미지 URL을 확인해 주세요.").optional(),sourceUrl:z.string().url().refine(v=>/^https:\/\/fin\.land\.naver\.com\/articles\/\d+(?:[/?#]|$)/.test(v)).optional(),confirmedAt:z.string().max(80).optional(),management:z.string().max(80).optional(),walk:z.string().max(80).optional(),direction:z.string().max(40).optional(),description:z.string().max(2000).optional()}).superRefine((v,c)=>{if(v.id.startsWith("test:")&&(!/^test:[1-5]$/.test(v.id)||v.name!=="TEST "+v.id.slice(5)||!v.trackable||v.sourceUrl||!v.description?.includes("테스트용 가상 매물")))c.addIssue({code:"custom",message:"테스트 ID와 이름·가상 매물 표시를 확인하세요."});if(v.deal==="전세"&&(v.rent!==0||v.priceOptions?.some(x=>x.rent!==0)))c.addIssue({code:"custom",message:"전세의 월세는 0이어야 합니다"})});
export type Listing=z.infer<typeof listingSchema>&{previous?:number;previousRent?:number;active:boolean;updated:string;history:{at:string;price:number;rent:number;priceText?:string}[]};
export const ruleSchema=z.object({name:z.string().trim().min(1).max(60),dong:z.string().refine(v=>v==="전체"||v==="동 정보 없음"||dongs.includes(v)),deal:z.enum(["전체","전세","월세"]),type:z.enum(["전체","원룸","오피스텔"]),maxPrice:z.number().finite().min(0).max(10000000),maxRent:z.number().finite().min(0).max(100000),minArea:z.number().finite().min(0).max(10000),enabled:z.boolean(),newMatch:z.boolean(),priceChange:z.boolean()});
export type Rule=z.infer<typeof ruleSchema>&{id:string};
export type Notice={id:string;ruleId:string;listingId:string;title:string;body:string;at:string;read:boolean;kind:"가격 변동"|"조건 일치"};
export type State={mode:"real";datasetId:string;sourceFile:string;sourceDate:string;listings:Listing[];rules:Rule[];notices:Notice[];runs:{at:string;source:string;added:number;changed:number;closed:number;alerts:number}[]};
export const money=(v:number)=>v>=10000?Number((v/10000).toFixed(4))+"억":v.toLocaleString()+"만";
export function priceLabel(l:Pick<Listing,"priceText"|"price"|"rent"|"deal">){return l.priceText??(l.deal+" "+money(l.price)+(l.deal==="월세"?" / "+money(l.rent):""))}
export function matches(l:Listing,r:Rule){return l.active&&(r.dong==="전체"||r.dong===l.dong)&&(r.deal==="전체"||r.deal===l.deal)&&(r.type==="전체"||r.type===l.type)&&(l.priceOptions??[{price:l.price,rent:l.rent}]).some(p=>p.price<=r.maxPrice&&(l.deal!=="월세"||p.rent<=r.maxRent))&&l.area>=r.minArea}
export function initial():State{return {mode:"real",datasetId:"",sourceFile:"",sourceDate:"",listings:[],rules:[],notices:[],runs:[]}}
export function importSnapshot(s:State,rows:z.infer<typeof listingSchema>[],source:string,at:string,sourceDate:string){
const ids=new Set(rows.map(x=>x.id));if(ids.size!==rows.length)throw new Error("중복 매물 ID가 있습니다. 파일을 수정하세요.");
const old=s.listings;const oldMap=new Map(old.map(x=>[x.id,x]));let added=0,changed=0,closed=old.filter(x=>x.trackable&&x.active&&!ids.has(x.id)).length;const notes:Notice[]=[];
const current=rows.map(row=>{const prev=oldMap.get(row.id);const canCompare=row.trackable&&(!prev||prev.trackable);const fresh=!prev||!prev.active;const priceChanged=!!prev&&prev.active&&canCompare&&JSON.stringify(prev.priceOptions??[{price:prev.price,rent:prev.rent}])!==JSON.stringify(row.priceOptions??[{price:row.price,rent:row.rent}]);if(fresh)added++;if(priceChanged)changed++;
const l:Listing={...row,active:true,updated:at,previous:priceChanged?prev!.price:prev?.previous,previousRent:priceChanged?prev!.rent:prev?.previousRent,history:!prev||!canCompare?[{at,price:row.price,rent:row.rent,priceText:row.priceText}]:priceChanged?[...prev.history,{at,price:row.price,rent:row.rent,priceText:row.priceText}].slice(-90):prev.history};
if(canCompare)for(const r of s.rules.filter(x=>x.enabled)){let kind:Notice["kind"]|undefined;const now=matches(l,r),before=prev?matches(prev,r):false;
if(priceChanged&&r.priceChange&&(now||before))kind="가격 변동";else if(r.newMatch&&now&&(!before||fresh))kind="조건 일치";
if(kind)notes.push({id:crypto.randomUUID(),ruleId:r.id,listingId:l.id,title:kind==="가격 변동"?l.name+" 가격이 바뀌었어요":r.name+"에 맞는 매물",body:kind==="가격 변동"?priceLabel(prev!)+" → "+priceLabel(l):l.dong+" · "+priceLabel(l)+" · "+l.area+"㎡",at,read:false,kind});}return l});
return {...s,sourceFile:source,sourceDate,listings:[...current,...old.filter(x=>x.trackable&&!ids.has(x.id)).map(x=>({...x,active:false}))],notices:[...notes,...s.notices].slice(0,1000),runs:[{at,source,added,changed,closed,alerts:notes.length},...s.runs].slice(0,90)} as State;
}

