'use client';
import {useEffect,useState} from 'react';
type Status={configured:boolean;lastDelivery:null|{ok:boolean;checkedAt:string;sourceFile?:string;count?:number;message?:string}};
const when=(s?:string|null)=>s?new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'기록 없음';
export function IntegrationPanel(){const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/admin/integration');if(!r.ok)throw new Error();setStatus(await r.json());}catch{setError('연결 상태를 불러오지 못했습니다.')}}
 useEffect(()=>{void load()},[]);
 async function sync(){setBusy(true);setError('');try{const r=await fetch('/api/admin/integration',{method:'POST'});const result=await r.json() as {ok:boolean;message?:string;error?:string};if(!r.ok||!result.ok)throw new Error(result.message??result.error??'전달에 실패했습니다.');await load();}catch(e){setError(e instanceof Error?e.message:'전달에 실패했습니다.');await load();}finally{setBusy(false)}}
 return <section className="panel padded"><h2>사용자 사이트 연결</h2>{error&&<p className="feedback error" role="alert">{error}</p>}<div className="settings-row"><div><strong>확정 매물 전달</strong><p>파일 반영 후 자동으로 전달합니다. 연결이 끊기면 기존 사용자 자료를 유지하며, 다시 전달할 수 있습니다.</p></div><span className="tag">{!status?'확인 중':status.configured?'연결 설정 완료':'설정 필요'}</span></div><div className="settings-row"><div><strong>마지막 전달 결과</strong><p>{status?.lastDelivery?(status.lastDelivery.ok?`${status.lastDelivery.sourceFile} · ${status.lastDelivery.count}건 전달 완료`:status.lastDelivery.message):'아직 전달 기록이 없습니다.'}</p><small>{when(status?.lastDelivery?.checkedAt)}</small></div><button className="primary" disabled={busy||!status?.configured} onClick={sync}>{busy?'전달 중…':'현재 확정 자료 다시 전달'}</button></div><div className="settings-row"><div><strong>고객 조건·관심 매물</strong><p>사용자 사이트에 보존하며 그곳에서 매물과 비교합니다. 운영자의 검토용 고객과는 별도입니다.</p></div></div><div className="settings-row"><div><strong>자동 수집·기기 푸시</strong><p>이번 연결에는 포함되지 않습니다. 매물 갱신은 운영자의 파일 반영으로 시작합니다.</p></div><span className="tag">미연결</span></div></section>;
}
type Housing={revision:number;feed:{notices:{id:string;title:string;url:string;publishedAt:string}[];checks:{source:string;status:string;message:string;checkedAt:string;lastSuccessAt:string|null}[];lastRunAt:string|null;schedule:{enabled:boolean;time:string;timezone:string;automationId:string|null}}};
export function ConnectedHousingPanel(){const [data,setData]=useState<Housing|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/admin/integration?view=housing');const j=await r.json() as Housing&{error?:string};if(!r.ok)throw new Error(j.error);setData(j);}catch(e){setError(e instanceof Error?e.message:'불러오지 못했습니다.');}finally{setBusy(false)}}
 useEffect(()=>{void load()},[]);
 return <section className="panel padded"><div className="panel-heading"><h2>청년·공공임대 운영 현황</h2><button disabled={busy} onClick={load}>{busy?'조회 중…':'결과 새로고침'}</button></div>{error&&<p className="feedback error" role="alert">{error}</p>}{data&&<><div className="settings-row"><div><strong>마지막 확인 시도</strong><p>{when(data.feed.lastRunAt)}</p></div><span className="tag">공고 {data.feed.notices.length}건</span></div><div className="settings-row"><div><strong>저장된 정기 확인 설정</strong><p>{data.feed.schedule.enabled?'사용':'중지'} · {data.feed.schedule.time} · {data.feed.schedule.timezone}</p><small>공고 저장소의 설정입니다. 스케줄러의 현재 가동 상태는 별도 확인이 필요합니다.</small></div></div>{data.feed.checks.map(c=><div className="settings-row" key={c.source}><div><strong>{{youth:'서울시 청년안심주택',sh:'SH',lh:'LH'}[c.source]??c.source}</strong><p>{c.message}</p><small>시도 {when(c.checkedAt)} · 정상 확인 {when(c.lastSuccessAt)}</small></div><span className="tag">{{ok:'정상 확인',partial:'일부 확인',error:'확인 실패'}[c.status]??c.status}</span></div>)}<h3>저장된 공고</h3>{data.feed.notices.map(n=><div className="settings-row" key={n.id}><a href={n.url} target="_blank" rel="noopener noreferrer">{n.title}</a><small>{n.publishedAt}</small></div>)}<p className="hint">사용자 화면에는 모집 공고만 제공합니다. 이 화면의 새로고침은 저장된 결과 조회이며, 기관 사이트 수집을 실행하지 않습니다.</p></>}</section>;
}
