'use client';
import {useEffect,useState} from 'react';
import type {AdminState} from '@/lib/admin';
import {dongs,matches,favoriteStatus,priceLabel,type Listing} from '@/lib/review-policy';
import Unverified from './unverified';
type Props={state:AdminState;busy:boolean;action:(a:string,b?:Record<string,unknown>)=>Promise<boolean>;open:(l:Listing)=>void};
const empty={alias:'',nickname:'',deal:'월세',maxPrice:'',maxRent:'',minArea:'',dongs:[] as string[],enabled:true};
export default function ReviewPanel({state,busy,action,open}:Props){const profiles=state.profiles??[];const [selected,setSelected]=useState(''),[editId,setEditId]=useState(''),[form,setForm]=useState(empty),[page,setPage]=useState(0),[query,setQuery]=useState('');
 useEffect(()=>{if(profiles.length&&!profiles.some(p=>p.id===selected))setSelected(profiles.at(-1)!.id)},[profiles,selected]);
 const profile=profiles.find(p=>p.id===selected);const matched=profile?state.listings.filter(l=>matches(l,profile.rule)):[];const unknown=profile?.rule.dongs.length?state.listings.filter(l=>l.dong==='동 정보 없음'&&matches(l,{...profile.rule,dongs:[]})):[];
 const visible=matched.filter(l=>[l.name,l.id,l.dong].join(' ').includes(query.trim()));const current=Math.min(page,Math.max(0,Math.ceil(visible.length/20)-1));
 const rows=(list:Listing[],favoriteView=false)=><div className="table-wrap"><table><thead><tr><th>매물 / 위치</th><th>금액</th><th>알림 상태</th><th>관심 관리</th><th></th></tr></thead><tbody>{list.map(l=>{const f=profile?.favorites.find(f=>f.listingId===l.id);return <tr key={l.id}><td><strong>{l.name}</strong><small>{l.dong} · {l.area}㎡</small></td><td>{priceLabel(l)}</td><td>{f?favoriteStatus(l,f,profile?.rule):'관심 저장 전'}</td><td><button disabled={busy} onClick={()=>action('favorite',{profileId:profile!.id,listingId:l.id,saved:!f})}>{f?'관심 해제':'관심 저장'}</button>{favoriteView&&f&&<button disabled={busy} onClick={()=>action('favorite-alert',{profileId:profile!.id,listingId:l.id,enabled:!f.alertsEnabled})}>{f.alertsEnabled?'알림 끄기':'알림 켜기'}</button>}</td><td><button onClick={()=>open(l)}>상세</button></td></tr>})}</tbody></table>{!list.length&&<div className="empty">해당 매물이 없습니다.</div>}</div>;
 return <><div className="note">운영자 검토용 고객입니다. 실제 고객 조건·하트는 미연동입니다. 고객별 조건은 1개이며 저장·수정만으로 알림을 생성하지 않습니다.</div><div className="two-columns"><section className="panel padded"><h2>{editId?'검토 조건 수정':'검토용 고객 등록'}</h2><form onSubmit={async e=>{e.preventDefault();const ok=await action('profile-save',{id:editId||undefined,profile:{alias:form.alias,nickname:form.nickname,rule:{deal:form.deal,maxPrice:Number(form.maxPrice),maxRent:form.deal==='월세'?Number(form.maxRent):null,minArea:form.minArea===''?null:Number(form.minArea),dongs:form.dongs,enabled:form.enabled}}});if(ok){setEditId('');setForm(empty)}}}>
 <label>고객 별칭<input required maxLength={60} placeholder="검토 고객 A" value={form.alias} onChange={e=>setForm({...form,alias:e.target.value})}/></label><label>알림 호칭 (선택)<input maxLength={24} value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><div className="form-grid"><label>거래 유형<select value={form.deal} onChange={e=>setForm({...form,deal:e.target.value})}><option>전세</option><option>월세</option></select></label><label>보증금 상한 (만원)<input type="number" min="0" max="10000000" required value={form.maxPrice} onChange={e=>setForm({...form,maxPrice:e.target.value})}/></label>{form.deal==='월세'&&<label>월세 상한 (만원)<input type="number" min="0" max="100000" required value={form.maxRent} onChange={e=>setForm({...form,maxRent:e.target.value})}/></label>}<label>최소 전용면적 (㎡, 선택)<input type="number" min="0" max="10000" step="0.1" value={form.minArea} onChange={e=>setForm({...form,minArea:e.target.value})}/></label></div><fieldset className="dong-picker"><legend>희망 동네 {form.dongs.length}/5 · 미선택 시 마포구 전체</legend>{dongs.map(d=><label key={d}><input type="checkbox" checked={form.dongs.includes(d)} disabled={!form.dongs.includes(d)&&form.dongs.length>=5} onChange={e=>setForm({...form,dongs:e.target.checked?[...form.dongs,d]:form.dongs.filter(x=>x!==d)})}/>{d}</label>)}</fieldset><label className="checkbox"><input type="checkbox" checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>알림 평가 사용</label><div className="button-row"><button className="primary" disabled={busy}>조건 저장</button>{editId&&<button type="button" onClick={()=>{setEditId('');setForm(empty)}}>수정 취소</button>}</div></form></section><section className="panel padded"><h2>검토용 고객 <span>{profiles.length}</span></h2>{!profiles.length&&<div className="empty">등록된 검토용 고객이 없습니다.</div>}{profiles.map(p=><div className={'rule-card '+(selected===p.id?'active-review':'')} key={p.id}><button className="rule-select" onClick={()=>{setSelected(p.id);setPage(0);setQuery('')}}><strong>{p.alias}</strong><small>{p.rule.deal} · {p.rule.dongs.join(', ')||'마포구 전체'}</small><span>일치 {state.listings.filter(l=>matches(l,p.rule)).length}건 · 관심 {p.favorites.length}건</span></button><div className="stack-buttons"><button disabled={busy} onClick={()=>{setSelected(p.id);setEditId(p.id);setForm({alias:p.alias,nickname:p.nickname,deal:p.rule.deal,maxPrice:String(p.rule.maxPrice),maxRent:p.rule.maxRent===null?'':String(p.rule.maxRent),minArea:p.rule.minArea===null?'':String(p.rule.minArea),dongs:[...p.rule.dongs],enabled:p.rule.enabled})}}>수정</button><button disabled={busy} onClick={()=>action('profile-toggle',{profileId:p.id,enabled:!p.rule.enabled})}>{p.rule.enabled?'사용 중':'전체 중지'}</button></div></div>)}</section></div>
 {profile&&<><section className="panel matches"><div className="panel-heading"><div><h2>{profile.alias} · 조건 일치 <span>{matched.length}</span></h2><p>확인된 동과 실제 보증금·월세 조합으로 판단합니다. 원룸·오피스텔을 모두 포함합니다.</p></div></div><Unverified key={profile.id+JSON.stringify(profile.rule)} rows={unknown} dong={profile.rule.dongs.join('·')} matched={matched.length} render={rows}/><div className="filters"><input type="search" aria-label="검토 매물 검색" value={query} placeholder="일치 매물 안에서 검색" onChange={e=>{setQuery(e.target.value);setPage(0)}}/></div>{rows(visible.slice(current*20,current*20+20))}<div className="pagination"><span>검색 결과 {visible.length}건</span><div><button disabled={!current} onClick={()=>setPage(current-1)}>이전</button><span>{current+1} / {Math.max(1,Math.ceil(visible.length/20))}</span><button disabled={(current+1)*20>=visible.length} onClick={()=>setPage(current+1)}>다음</button></div></div></section><section className="panel matches"><div className="panel-heading"><div><h2>{profile.alias} · 검토용 관심 매물</h2><p>조건 이탈·미확인 중에도 관심 저장은 유지합니다. 수동으로 끈 알림은 자동으로 켜지지 않습니다.</p></div></div>{rows(state.listings.filter(l=>profile.favorites.some(f=>f.listingId===l.id)),true)}</section></>}
 <details className="panel padded matches"><summary>이전 조건 보관함 · {state.rules.length}개</summary><p>이전 조건은 자동 변환·삭제하지 않았습니다. 새 규칙의 알림 평가에는 사용하지 않습니다.</p>{state.rules.map(r=><div className="settings-row" key={r.id}><div><strong>{r.name}</strong><p>{r.dong} · {r.type} · {r.deal} · 보증금 {r.maxPrice}만원 / 월세 {r.maxRent}만원 · 최소 {r.minArea}㎡ · {r.enabled?'기존 사용 설정':'기존 중지 설정'}</p></div><span className="tag">보관</span></div>)}</details></>
}
