import assert from 'node:assert/strict';
// @ts-expect-error Node's native TypeScript runner requires the explicit extension.
import {housingId,housingNoticeInput,housingUpdateInput,mergeHousingFeed,noticeStatus} from '../lib/public-housing.ts';
const input=housingNoticeInput.parse({source:'youth',title:'마포구 청년주택 모집',url:'https://soco.seoul.go.kr/youth/bbs/BMSR00015/view.do?boardId=100&menuNo=400008',publishedAt:'2026-10-06',address:'마포구 염리동',mapoEvidence:'공급 위치 서울 마포구 염리동',category:'청년안심주택',summary:'공식 모집 공고를 확인하세요.',applicationStart:'2026-10-07T09:00:00+09:00',applicationEnd:'2026-10-08T18:00:00+09:00',applicationLabel:'10월 7~8일',eligibility:'공식 공고 확인',withdrawn:false});
assert.equal(noticeStatus(input,Date.parse('2026-10-06T08:00:00+09:00')),'접수 예정');
assert.equal(noticeStatus(input,Date.parse('2026-10-07T09:00:00+09:00')),'접수 중');
assert.equal(noticeStatus(input,Date.parse('2026-10-08T18:00:01+09:00')),'접수 마감');
assert.equal(noticeStatus({...input,applicationEnd:null},Date.parse('2026-10-08T18:00:01+09:00')),'일정 확인 필요');
assert.equal(noticeStatus({...input,withdrawn:true}),'모집 취소');
assert.equal(housingId('youth','https://soco.seoul.go.kr.evil.test/youth/bbs/BMSR00015/view.do?boardId=100'),null);
assert.equal(housingId('youth','javascript:alert(1)'),null);
assert.equal(housingId('youth',input.url+'&pageIndex=3'),'youth:100');
assert.equal(housingNoticeInput.safeParse({...input,mapoEvidence:'강동구'}).success,false);
assert.equal(housingNoticeInput.safeParse({...input,publishedAt:'2026-02-30'}).success,false);
const checks=[{source:'youth',status:'ok',message:'신규 상세 확인'},{source:'sh',status:'partial',message:'첨부 목록 확인 필요'},{source:'lh',status:'error',message:'연결 확인 실패'}] as const;
const update=housingUpdateInput.parse({revision:0,notices:[input],checks});
const empty={notices:[],checks:[],lastRunAt:null,schedule:{enabled:false,time:'08:00',timezone:'Asia/Seoul',automationId:null}} as const;
const added=mergeHousingFeed(structuredClone({...empty,notices:[],checks:[]}),update,'2026-10-06T01:00:00Z');
assert.equal(added.added,1);
const again=mergeHousingFeed(added.feed,update,'2026-10-07T01:00:00Z');
assert.equal(again.added,0);assert.equal(again.changed,0);assert.equal(again.feed.notices.length,1);
assert.equal(again.feed.notices[0].firstSeenAt,'2026-10-06T01:00:00Z');
const changed=mergeHousingFeed(again.feed,{...update,notices:[{...input,applicationEnd:'2026-10-09T18:00:00+09:00'}]},'2026-10-08T01:00:00Z');
assert.equal(changed.changed,1);
const missing=mergeHousingFeed(changed.feed,{...update,notices:[]},'2026-10-09T01:00:00Z');
assert.equal(missing.feed.notices.length,1);
assert.equal(housingUpdateInput.safeParse({...update,notices:[input,input]}).success,false);
assert.equal(housingUpdateInput.safeParse({...update,checks:checks.map(c=>({...c,source:'youth'}))}).success,false);
assert.equal(housingUpdateInput.safeParse({...update,checks:checks.map(c=>c.source==='youth'?{...c,status:'error'}:c)}).success,false);
console.log('Public housing: dates, trusted links, deduplication, corrections, retention and validation passed.');
