import assert from 'node:assert/strict';
import fs from 'node:fs';
import ExcelJS from 'exceljs';
import {parseCollectedRows} from '../lib/collected';
import {importSnapshot,initial,matches,type Rule} from '../lib/model';
import {parseCSV} from '../lib/csv';
async function main(){const b=new ExcelJS.Workbook();await b.xlsx.readFile('C:/Users/Administrator/Downloads/SINGLE_20261006_130231.xlsx');const sh=b.getWorksheet('Sheet1')!;const raw:unknown[][]=[];sh.eachRow({includeEmpty:true},r=>raw.push(Array.from({length:sh.columnCount},(_,i)=>r.getCell(i+1).text)));const parsed=parseCollectedRows(raw,'SINGLE_20261006_130231.xlsx');const rows=parsed.rows;assert.equal(rows.length,1003);assert.equal(rows.filter(x=>x.type==='원룸').length,604);assert.equal(rows.filter(x=>x.type==='오피스텔').length,399);assert.equal(rows.filter(x=>x.deal==='전세').length,222);assert.equal(rows.filter(x=>x.deal==='월세').length,781);assert.equal(rows.filter(x=>x.trackable).length,965);assert.equal(rows.filter(x=>!x.sourceUrl).length,38);const baseline=JSON.parse(fs.readFileSync('data/2026-10-06.json','utf8'));assert.deepEqual(JSON.parse(JSON.stringify(rows.map(({sourceSheet,sourceCollectedAt,...l})=>l))),baseline.map((l:any)=>({...l,description:l.description?.trim()||undefined})).map((l:any)=>JSON.parse(JSON.stringify(l))));assert.throws(()=>parseCollectedRows([raw[0],raw[1],raw[1]],'SINGLE_20261006_130231.xlsx'),/중복/);assert.throws(()=>parseCollectedRows([['LABEL-1'],raw[1]],'SINGLE_20261006_130231.xlsx'),/열 구성/);
let s=importSnapshot(initial(),rows,'first','2026-10-06T04:02:31Z',parsed.sourceDate);assert.equal(importSnapshot(s,rows,'same','2026-10-07T00:00:00Z',parsed.sourceDate).runs[0].changed,0);const target=rows.find(x=>x.trackable)!;const changed=rows.map(x=>x.id===target.id?{...x,price:x.price+100,priceOptions:[{price:x.price+100,rent:x.rent}]}:x);assert.equal(importSnapshot(s,changed,'new','2026-10-07T00:00:00Z','2026-10-07').runs[0].changed,1);assert.equal(importSnapshot(s,rows.filter(x=>x.id!==target.id),'missing','2026-10-07T00:00:00Z','2026-10-07').runs[0].closed,1);
const r:Rule={id:'t',name:'test',dong:'전체',type:'전체',deal:'월세',enabled:true,newMatch:true,priceChange:true,minArea:0,maxPrice:1000,maxRent:50};const range={...s.listings[0],active:true,deal:'월세' as const,priceOptions:[{price:500,rent:100},{price:2000,rent:30}]};assert.equal(matches(range,r),false);assert.equal(matches(range,{...r,maxPrice:2000}),true);assert.deepEqual(parseCSV('a,b\r\n"hello, world","line\nnext"'),[['a','b'],['hello, world','line\nnext']]);assert.throws(()=>parseCSV('a,"unfinished'));fs.writeFileSync('.sites-runtime/source-rows.json',JSON.stringify(raw));console.log(JSON.stringify({verified:true,total:1003,oneRoom:604,officetel:399,jeonse:222,monthly:781,trackable:965,noLink:38,bytes:Buffer.byteLength(JSON.stringify(s)),checks:'source parity, duplicate/header validation, unchanged/change/missing comparison, paired range matching, CSV quoting'}));}main();


